// Code generated by SQLBoiler 4.4.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Balance                string
	BFOrders               string
	BFTransactions         string
	BittrexDepositHistory  string
	BittrexOrderHistory    string
	BittrexWithdrawHistory string
	CoincheckHistory       string
	Config                 string
	CryptactCustom         string
	Entry                  string
	Event                  string
	MarketPrice            string
	Method                 string
	PoloniexDeposits       string
	PoloniexDistributions  string
	PoloniexTrades         string
	PoloniexWithdrawals    string
	Symbols                string
	Transactions           string
	Transition             string
}{
	Balance:                "balance",
	BFOrders:               "bf_orders",
	BFTransactions:         "bf_transactions",
	BittrexDepositHistory:  "bittrex_deposit_history",
	BittrexOrderHistory:    "bittrex_order_history",
	BittrexWithdrawHistory: "bittrex_withdraw_history",
	CoincheckHistory:       "coincheck_history",
	Config:                 "config",
	CryptactCustom:         "cryptact_custom",
	Entry:                  "entry",
	Event:                  "event",
	MarketPrice:            "market_price",
	Method:                 "method",
	PoloniexDeposits:       "poloniex_deposits",
	PoloniexDistributions:  "poloniex_distributions",
	PoloniexTrades:         "poloniex_trades",
	PoloniexWithdrawals:    "poloniex_withdrawals",
	Symbols:                "symbols",
	Transactions:           "transactions",
	Transition:             "transition",
}
