// Code generated by SQLBoiler 4.4.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/v4/types"
	"github.com/volatiletech/strmangle"
)

// PoloniexDeposit is an object representing the database table.
type PoloniexDeposit struct {
	ID       int           `boil:"id" json:"id" toml:"id" yaml:"id"`
	Date     time.Time     `boil:"date" json:"date" toml:"date" yaml:"date"`
	Currency string        `boil:"currency" json:"currency" toml:"currency" yaml:"currency"`
	Amount   types.Decimal `boil:"amount" json:"amount" toml:"amount" yaml:"amount"`
	Address  string        `boil:"address" json:"address" toml:"address" yaml:"address"`
	Status   string        `boil:"status" json:"status" toml:"status" yaml:"status"`

	R *poloniexDepositR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L poloniexDepositL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PoloniexDepositColumns = struct {
	ID       string
	Date     string
	Currency string
	Amount   string
	Address  string
	Status   string
}{
	ID:       "id",
	Date:     "date",
	Currency: "currency",
	Amount:   "amount",
	Address:  "address",
	Status:   "status",
}

// Generated where

var PoloniexDepositWhere = struct {
	ID       whereHelperint
	Date     whereHelpertime_Time
	Currency whereHelperstring
	Amount   whereHelpertypes_Decimal
	Address  whereHelperstring
	Status   whereHelperstring
}{
	ID:       whereHelperint{field: "`poloniex_deposits`.`id`"},
	Date:     whereHelpertime_Time{field: "`poloniex_deposits`.`date`"},
	Currency: whereHelperstring{field: "`poloniex_deposits`.`currency`"},
	Amount:   whereHelpertypes_Decimal{field: "`poloniex_deposits`.`amount`"},
	Address:  whereHelperstring{field: "`poloniex_deposits`.`address`"},
	Status:   whereHelperstring{field: "`poloniex_deposits`.`status`"},
}

// PoloniexDepositRels is where relationship names are stored.
var PoloniexDepositRels = struct {
}{}

// poloniexDepositR is where relationships are stored.
type poloniexDepositR struct {
}

// NewStruct creates a new relationship struct
func (*poloniexDepositR) NewStruct() *poloniexDepositR {
	return &poloniexDepositR{}
}

// poloniexDepositL is where Load methods for each relationship are stored.
type poloniexDepositL struct{}

var (
	poloniexDepositAllColumns            = []string{"id", "date", "currency", "amount", "address", "status"}
	poloniexDepositColumnsWithoutDefault = []string{"date", "currency", "amount", "address", "status"}
	poloniexDepositColumnsWithDefault    = []string{"id"}
	poloniexDepositPrimaryKeyColumns     = []string{"id"}
)

type (
	// PoloniexDepositSlice is an alias for a slice of pointers to PoloniexDeposit.
	// This should generally be used opposed to []PoloniexDeposit.
	PoloniexDepositSlice []*PoloniexDeposit
	// PoloniexDepositHook is the signature for custom PoloniexDeposit hook methods
	PoloniexDepositHook func(context.Context, boil.ContextExecutor, *PoloniexDeposit) error

	poloniexDepositQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	poloniexDepositType                 = reflect.TypeOf(&PoloniexDeposit{})
	poloniexDepositMapping              = queries.MakeStructMapping(poloniexDepositType)
	poloniexDepositPrimaryKeyMapping, _ = queries.BindMapping(poloniexDepositType, poloniexDepositMapping, poloniexDepositPrimaryKeyColumns)
	poloniexDepositInsertCacheMut       sync.RWMutex
	poloniexDepositInsertCache          = make(map[string]insertCache)
	poloniexDepositUpdateCacheMut       sync.RWMutex
	poloniexDepositUpdateCache          = make(map[string]updateCache)
	poloniexDepositUpsertCacheMut       sync.RWMutex
	poloniexDepositUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var poloniexDepositBeforeInsertHooks []PoloniexDepositHook
var poloniexDepositBeforeUpdateHooks []PoloniexDepositHook
var poloniexDepositBeforeDeleteHooks []PoloniexDepositHook
var poloniexDepositBeforeUpsertHooks []PoloniexDepositHook

var poloniexDepositAfterInsertHooks []PoloniexDepositHook
var poloniexDepositAfterSelectHooks []PoloniexDepositHook
var poloniexDepositAfterUpdateHooks []PoloniexDepositHook
var poloniexDepositAfterDeleteHooks []PoloniexDepositHook
var poloniexDepositAfterUpsertHooks []PoloniexDepositHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *PoloniexDeposit) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range poloniexDepositBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *PoloniexDeposit) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range poloniexDepositBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *PoloniexDeposit) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range poloniexDepositBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *PoloniexDeposit) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range poloniexDepositBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *PoloniexDeposit) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range poloniexDepositAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *PoloniexDeposit) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range poloniexDepositAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *PoloniexDeposit) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range poloniexDepositAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *PoloniexDeposit) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range poloniexDepositAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *PoloniexDeposit) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range poloniexDepositAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPoloniexDepositHook registers your hook function for all future operations.
func AddPoloniexDepositHook(hookPoint boil.HookPoint, poloniexDepositHook PoloniexDepositHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		poloniexDepositBeforeInsertHooks = append(poloniexDepositBeforeInsertHooks, poloniexDepositHook)
	case boil.BeforeUpdateHook:
		poloniexDepositBeforeUpdateHooks = append(poloniexDepositBeforeUpdateHooks, poloniexDepositHook)
	case boil.BeforeDeleteHook:
		poloniexDepositBeforeDeleteHooks = append(poloniexDepositBeforeDeleteHooks, poloniexDepositHook)
	case boil.BeforeUpsertHook:
		poloniexDepositBeforeUpsertHooks = append(poloniexDepositBeforeUpsertHooks, poloniexDepositHook)
	case boil.AfterInsertHook:
		poloniexDepositAfterInsertHooks = append(poloniexDepositAfterInsertHooks, poloniexDepositHook)
	case boil.AfterSelectHook:
		poloniexDepositAfterSelectHooks = append(poloniexDepositAfterSelectHooks, poloniexDepositHook)
	case boil.AfterUpdateHook:
		poloniexDepositAfterUpdateHooks = append(poloniexDepositAfterUpdateHooks, poloniexDepositHook)
	case boil.AfterDeleteHook:
		poloniexDepositAfterDeleteHooks = append(poloniexDepositAfterDeleteHooks, poloniexDepositHook)
	case boil.AfterUpsertHook:
		poloniexDepositAfterUpsertHooks = append(poloniexDepositAfterUpsertHooks, poloniexDepositHook)
	}
}

// One returns a single poloniexDeposit record from the query.
func (q poloniexDepositQuery) One(ctx context.Context, exec boil.ContextExecutor) (*PoloniexDeposit, error) {
	o := &PoloniexDeposit{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for poloniex_deposits")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all PoloniexDeposit records from the query.
func (q poloniexDepositQuery) All(ctx context.Context, exec boil.ContextExecutor) (PoloniexDepositSlice, error) {
	var o []*PoloniexDeposit

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to PoloniexDeposit slice")
	}

	if len(poloniexDepositAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all PoloniexDeposit records in the query.
func (q poloniexDepositQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count poloniex_deposits rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q poloniexDepositQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if poloniex_deposits exists")
	}

	return count > 0, nil
}

// PoloniexDeposits retrieves all the records using an executor.
func PoloniexDeposits(mods ...qm.QueryMod) poloniexDepositQuery {
	mods = append(mods, qm.From("`poloniex_deposits`"))
	return poloniexDepositQuery{NewQuery(mods...)}
}

// FindPoloniexDeposit retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPoloniexDeposit(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*PoloniexDeposit, error) {
	poloniexDepositObj := &PoloniexDeposit{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `poloniex_deposits` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, poloniexDepositObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from poloniex_deposits")
	}

	return poloniexDepositObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *PoloniexDeposit) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no poloniex_deposits provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(poloniexDepositColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	poloniexDepositInsertCacheMut.RLock()
	cache, cached := poloniexDepositInsertCache[key]
	poloniexDepositInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			poloniexDepositAllColumns,
			poloniexDepositColumnsWithDefault,
			poloniexDepositColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(poloniexDepositType, poloniexDepositMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(poloniexDepositType, poloniexDepositMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `poloniex_deposits` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `poloniex_deposits` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `poloniex_deposits` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, poloniexDepositPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into poloniex_deposits")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == poloniexDepositMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for poloniex_deposits")
	}

CacheNoHooks:
	if !cached {
		poloniexDepositInsertCacheMut.Lock()
		poloniexDepositInsertCache[key] = cache
		poloniexDepositInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the PoloniexDeposit.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *PoloniexDeposit) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	poloniexDepositUpdateCacheMut.RLock()
	cache, cached := poloniexDepositUpdateCache[key]
	poloniexDepositUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			poloniexDepositAllColumns,
			poloniexDepositPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update poloniex_deposits, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `poloniex_deposits` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, poloniexDepositPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(poloniexDepositType, poloniexDepositMapping, append(wl, poloniexDepositPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update poloniex_deposits row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for poloniex_deposits")
	}

	if !cached {
		poloniexDepositUpdateCacheMut.Lock()
		poloniexDepositUpdateCache[key] = cache
		poloniexDepositUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q poloniexDepositQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for poloniex_deposits")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for poloniex_deposits")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PoloniexDepositSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), poloniexDepositPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `poloniex_deposits` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, poloniexDepositPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in poloniexDeposit slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all poloniexDeposit")
	}
	return rowsAff, nil
}

var mySQLPoloniexDepositUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *PoloniexDeposit) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no poloniex_deposits provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(poloniexDepositColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLPoloniexDepositUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	poloniexDepositUpsertCacheMut.RLock()
	cache, cached := poloniexDepositUpsertCache[key]
	poloniexDepositUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			poloniexDepositAllColumns,
			poloniexDepositColumnsWithDefault,
			poloniexDepositColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			poloniexDepositAllColumns,
			poloniexDepositPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert poloniex_deposits, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`poloniex_deposits`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `poloniex_deposits` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(poloniexDepositType, poloniexDepositMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(poloniexDepositType, poloniexDepositMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for poloniex_deposits")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == poloniexDepositMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(poloniexDepositType, poloniexDepositMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for poloniex_deposits")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for poloniex_deposits")
	}

CacheNoHooks:
	if !cached {
		poloniexDepositUpsertCacheMut.Lock()
		poloniexDepositUpsertCache[key] = cache
		poloniexDepositUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single PoloniexDeposit record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *PoloniexDeposit) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no PoloniexDeposit provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), poloniexDepositPrimaryKeyMapping)
	sql := "DELETE FROM `poloniex_deposits` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from poloniex_deposits")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for poloniex_deposits")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q poloniexDepositQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no poloniexDepositQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from poloniex_deposits")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for poloniex_deposits")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PoloniexDepositSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(poloniexDepositBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), poloniexDepositPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `poloniex_deposits` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, poloniexDepositPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from poloniexDeposit slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for poloniex_deposits")
	}

	if len(poloniexDepositAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *PoloniexDeposit) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPoloniexDeposit(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PoloniexDepositSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PoloniexDepositSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), poloniexDepositPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `poloniex_deposits`.* FROM `poloniex_deposits` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, poloniexDepositPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in PoloniexDepositSlice")
	}

	*o = slice

	return nil
}

// PoloniexDepositExists checks if the PoloniexDeposit row exists.
func PoloniexDepositExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `poloniex_deposits` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if poloniex_deposits exists")
	}

	return exists, nil
}
