// Code generated by SQLBoiler 4.4.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/v4/types"
	"github.com/volatiletech/strmangle"
)

// PoloniexWithdrawal is an object representing the database table.
type PoloniexWithdrawal struct {
	ID             int           `boil:"id" json:"id" toml:"id" yaml:"id"`
	Date           time.Time     `boil:"date" json:"date" toml:"date" yaml:"date"`
	Currency       string        `boil:"currency" json:"currency" toml:"currency" yaml:"currency"`
	Amount         types.Decimal `boil:"amount" json:"amount" toml:"amount" yaml:"amount"`
	FeeDeducted    types.Decimal `boil:"fee_deducted" json:"fee_deducted" toml:"fee_deducted" yaml:"fee_deducted"`
	AmountMinusFee types.Decimal `boil:"amount_minus_fee" json:"amount_minus_fee" toml:"amount_minus_fee" yaml:"amount_minus_fee"`
	Address        string        `boil:"address" json:"address" toml:"address" yaml:"address"`
	Status         string        `boil:"status" json:"status" toml:"status" yaml:"status"`

	R *poloniexWithdrawalR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L poloniexWithdrawalL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PoloniexWithdrawalColumns = struct {
	ID             string
	Date           string
	Currency       string
	Amount         string
	FeeDeducted    string
	AmountMinusFee string
	Address        string
	Status         string
}{
	ID:             "id",
	Date:           "date",
	Currency:       "currency",
	Amount:         "amount",
	FeeDeducted:    "fee_deducted",
	AmountMinusFee: "amount_minus_fee",
	Address:        "address",
	Status:         "status",
}

// Generated where

var PoloniexWithdrawalWhere = struct {
	ID             whereHelperint
	Date           whereHelpertime_Time
	Currency       whereHelperstring
	Amount         whereHelpertypes_Decimal
	FeeDeducted    whereHelpertypes_Decimal
	AmountMinusFee whereHelpertypes_Decimal
	Address        whereHelperstring
	Status         whereHelperstring
}{
	ID:             whereHelperint{field: "`poloniex_withdrawals`.`id`"},
	Date:           whereHelpertime_Time{field: "`poloniex_withdrawals`.`date`"},
	Currency:       whereHelperstring{field: "`poloniex_withdrawals`.`currency`"},
	Amount:         whereHelpertypes_Decimal{field: "`poloniex_withdrawals`.`amount`"},
	FeeDeducted:    whereHelpertypes_Decimal{field: "`poloniex_withdrawals`.`fee_deducted`"},
	AmountMinusFee: whereHelpertypes_Decimal{field: "`poloniex_withdrawals`.`amount_minus_fee`"},
	Address:        whereHelperstring{field: "`poloniex_withdrawals`.`address`"},
	Status:         whereHelperstring{field: "`poloniex_withdrawals`.`status`"},
}

// PoloniexWithdrawalRels is where relationship names are stored.
var PoloniexWithdrawalRels = struct {
}{}

// poloniexWithdrawalR is where relationships are stored.
type poloniexWithdrawalR struct {
}

// NewStruct creates a new relationship struct
func (*poloniexWithdrawalR) NewStruct() *poloniexWithdrawalR {
	return &poloniexWithdrawalR{}
}

// poloniexWithdrawalL is where Load methods for each relationship are stored.
type poloniexWithdrawalL struct{}

var (
	poloniexWithdrawalAllColumns            = []string{"id", "date", "currency", "amount", "fee_deducted", "amount_minus_fee", "address", "status"}
	poloniexWithdrawalColumnsWithoutDefault = []string{"date", "currency", "amount", "fee_deducted", "amount_minus_fee", "address", "status"}
	poloniexWithdrawalColumnsWithDefault    = []string{"id"}
	poloniexWithdrawalPrimaryKeyColumns     = []string{"id"}
)

type (
	// PoloniexWithdrawalSlice is an alias for a slice of pointers to PoloniexWithdrawal.
	// This should generally be used opposed to []PoloniexWithdrawal.
	PoloniexWithdrawalSlice []*PoloniexWithdrawal
	// PoloniexWithdrawalHook is the signature for custom PoloniexWithdrawal hook methods
	PoloniexWithdrawalHook func(context.Context, boil.ContextExecutor, *PoloniexWithdrawal) error

	poloniexWithdrawalQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	poloniexWithdrawalType                 = reflect.TypeOf(&PoloniexWithdrawal{})
	poloniexWithdrawalMapping              = queries.MakeStructMapping(poloniexWithdrawalType)
	poloniexWithdrawalPrimaryKeyMapping, _ = queries.BindMapping(poloniexWithdrawalType, poloniexWithdrawalMapping, poloniexWithdrawalPrimaryKeyColumns)
	poloniexWithdrawalInsertCacheMut       sync.RWMutex
	poloniexWithdrawalInsertCache          = make(map[string]insertCache)
	poloniexWithdrawalUpdateCacheMut       sync.RWMutex
	poloniexWithdrawalUpdateCache          = make(map[string]updateCache)
	poloniexWithdrawalUpsertCacheMut       sync.RWMutex
	poloniexWithdrawalUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var poloniexWithdrawalBeforeInsertHooks []PoloniexWithdrawalHook
var poloniexWithdrawalBeforeUpdateHooks []PoloniexWithdrawalHook
var poloniexWithdrawalBeforeDeleteHooks []PoloniexWithdrawalHook
var poloniexWithdrawalBeforeUpsertHooks []PoloniexWithdrawalHook

var poloniexWithdrawalAfterInsertHooks []PoloniexWithdrawalHook
var poloniexWithdrawalAfterSelectHooks []PoloniexWithdrawalHook
var poloniexWithdrawalAfterUpdateHooks []PoloniexWithdrawalHook
var poloniexWithdrawalAfterDeleteHooks []PoloniexWithdrawalHook
var poloniexWithdrawalAfterUpsertHooks []PoloniexWithdrawalHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *PoloniexWithdrawal) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range poloniexWithdrawalBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *PoloniexWithdrawal) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range poloniexWithdrawalBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *PoloniexWithdrawal) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range poloniexWithdrawalBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *PoloniexWithdrawal) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range poloniexWithdrawalBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *PoloniexWithdrawal) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range poloniexWithdrawalAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *PoloniexWithdrawal) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range poloniexWithdrawalAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *PoloniexWithdrawal) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range poloniexWithdrawalAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *PoloniexWithdrawal) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range poloniexWithdrawalAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *PoloniexWithdrawal) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range poloniexWithdrawalAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPoloniexWithdrawalHook registers your hook function for all future operations.
func AddPoloniexWithdrawalHook(hookPoint boil.HookPoint, poloniexWithdrawalHook PoloniexWithdrawalHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		poloniexWithdrawalBeforeInsertHooks = append(poloniexWithdrawalBeforeInsertHooks, poloniexWithdrawalHook)
	case boil.BeforeUpdateHook:
		poloniexWithdrawalBeforeUpdateHooks = append(poloniexWithdrawalBeforeUpdateHooks, poloniexWithdrawalHook)
	case boil.BeforeDeleteHook:
		poloniexWithdrawalBeforeDeleteHooks = append(poloniexWithdrawalBeforeDeleteHooks, poloniexWithdrawalHook)
	case boil.BeforeUpsertHook:
		poloniexWithdrawalBeforeUpsertHooks = append(poloniexWithdrawalBeforeUpsertHooks, poloniexWithdrawalHook)
	case boil.AfterInsertHook:
		poloniexWithdrawalAfterInsertHooks = append(poloniexWithdrawalAfterInsertHooks, poloniexWithdrawalHook)
	case boil.AfterSelectHook:
		poloniexWithdrawalAfterSelectHooks = append(poloniexWithdrawalAfterSelectHooks, poloniexWithdrawalHook)
	case boil.AfterUpdateHook:
		poloniexWithdrawalAfterUpdateHooks = append(poloniexWithdrawalAfterUpdateHooks, poloniexWithdrawalHook)
	case boil.AfterDeleteHook:
		poloniexWithdrawalAfterDeleteHooks = append(poloniexWithdrawalAfterDeleteHooks, poloniexWithdrawalHook)
	case boil.AfterUpsertHook:
		poloniexWithdrawalAfterUpsertHooks = append(poloniexWithdrawalAfterUpsertHooks, poloniexWithdrawalHook)
	}
}

// One returns a single poloniexWithdrawal record from the query.
func (q poloniexWithdrawalQuery) One(ctx context.Context, exec boil.ContextExecutor) (*PoloniexWithdrawal, error) {
	o := &PoloniexWithdrawal{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for poloniex_withdrawals")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all PoloniexWithdrawal records from the query.
func (q poloniexWithdrawalQuery) All(ctx context.Context, exec boil.ContextExecutor) (PoloniexWithdrawalSlice, error) {
	var o []*PoloniexWithdrawal

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to PoloniexWithdrawal slice")
	}

	if len(poloniexWithdrawalAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all PoloniexWithdrawal records in the query.
func (q poloniexWithdrawalQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count poloniex_withdrawals rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q poloniexWithdrawalQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if poloniex_withdrawals exists")
	}

	return count > 0, nil
}

// PoloniexWithdrawals retrieves all the records using an executor.
func PoloniexWithdrawals(mods ...qm.QueryMod) poloniexWithdrawalQuery {
	mods = append(mods, qm.From("`poloniex_withdrawals`"))
	return poloniexWithdrawalQuery{NewQuery(mods...)}
}

// FindPoloniexWithdrawal retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPoloniexWithdrawal(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*PoloniexWithdrawal, error) {
	poloniexWithdrawalObj := &PoloniexWithdrawal{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `poloniex_withdrawals` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, poloniexWithdrawalObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from poloniex_withdrawals")
	}

	return poloniexWithdrawalObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *PoloniexWithdrawal) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no poloniex_withdrawals provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(poloniexWithdrawalColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	poloniexWithdrawalInsertCacheMut.RLock()
	cache, cached := poloniexWithdrawalInsertCache[key]
	poloniexWithdrawalInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			poloniexWithdrawalAllColumns,
			poloniexWithdrawalColumnsWithDefault,
			poloniexWithdrawalColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(poloniexWithdrawalType, poloniexWithdrawalMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(poloniexWithdrawalType, poloniexWithdrawalMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `poloniex_withdrawals` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `poloniex_withdrawals` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `poloniex_withdrawals` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, poloniexWithdrawalPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into poloniex_withdrawals")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == poloniexWithdrawalMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for poloniex_withdrawals")
	}

CacheNoHooks:
	if !cached {
		poloniexWithdrawalInsertCacheMut.Lock()
		poloniexWithdrawalInsertCache[key] = cache
		poloniexWithdrawalInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the PoloniexWithdrawal.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *PoloniexWithdrawal) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	poloniexWithdrawalUpdateCacheMut.RLock()
	cache, cached := poloniexWithdrawalUpdateCache[key]
	poloniexWithdrawalUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			poloniexWithdrawalAllColumns,
			poloniexWithdrawalPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update poloniex_withdrawals, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `poloniex_withdrawals` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, poloniexWithdrawalPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(poloniexWithdrawalType, poloniexWithdrawalMapping, append(wl, poloniexWithdrawalPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update poloniex_withdrawals row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for poloniex_withdrawals")
	}

	if !cached {
		poloniexWithdrawalUpdateCacheMut.Lock()
		poloniexWithdrawalUpdateCache[key] = cache
		poloniexWithdrawalUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q poloniexWithdrawalQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for poloniex_withdrawals")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for poloniex_withdrawals")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PoloniexWithdrawalSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), poloniexWithdrawalPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `poloniex_withdrawals` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, poloniexWithdrawalPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in poloniexWithdrawal slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all poloniexWithdrawal")
	}
	return rowsAff, nil
}

var mySQLPoloniexWithdrawalUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *PoloniexWithdrawal) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no poloniex_withdrawals provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(poloniexWithdrawalColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLPoloniexWithdrawalUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	poloniexWithdrawalUpsertCacheMut.RLock()
	cache, cached := poloniexWithdrawalUpsertCache[key]
	poloniexWithdrawalUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			poloniexWithdrawalAllColumns,
			poloniexWithdrawalColumnsWithDefault,
			poloniexWithdrawalColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			poloniexWithdrawalAllColumns,
			poloniexWithdrawalPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert poloniex_withdrawals, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`poloniex_withdrawals`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `poloniex_withdrawals` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(poloniexWithdrawalType, poloniexWithdrawalMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(poloniexWithdrawalType, poloniexWithdrawalMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for poloniex_withdrawals")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == poloniexWithdrawalMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(poloniexWithdrawalType, poloniexWithdrawalMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for poloniex_withdrawals")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for poloniex_withdrawals")
	}

CacheNoHooks:
	if !cached {
		poloniexWithdrawalUpsertCacheMut.Lock()
		poloniexWithdrawalUpsertCache[key] = cache
		poloniexWithdrawalUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single PoloniexWithdrawal record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *PoloniexWithdrawal) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no PoloniexWithdrawal provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), poloniexWithdrawalPrimaryKeyMapping)
	sql := "DELETE FROM `poloniex_withdrawals` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from poloniex_withdrawals")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for poloniex_withdrawals")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q poloniexWithdrawalQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no poloniexWithdrawalQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from poloniex_withdrawals")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for poloniex_withdrawals")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PoloniexWithdrawalSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(poloniexWithdrawalBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), poloniexWithdrawalPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `poloniex_withdrawals` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, poloniexWithdrawalPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from poloniexWithdrawal slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for poloniex_withdrawals")
	}

	if len(poloniexWithdrawalAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *PoloniexWithdrawal) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPoloniexWithdrawal(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PoloniexWithdrawalSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PoloniexWithdrawalSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), poloniexWithdrawalPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `poloniex_withdrawals`.* FROM `poloniex_withdrawals` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, poloniexWithdrawalPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in PoloniexWithdrawalSlice")
	}

	*o = slice

	return nil
}

// PoloniexWithdrawalExists checks if the PoloniexWithdrawal row exists.
func PoloniexWithdrawalExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `poloniex_withdrawals` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if poloniex_withdrawals exists")
	}

	return exists, nil
}
